import {
  ClerkProvider,
} from '@clerk/nextjs';
import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import Script from 'next/script';




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
    <html lang="en">

<head>
  <link rel="stylesheet" 
  href="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.css"/>
</head>




      <body> 

       <Script src="https://cdn.snipcart.com/themes/v3.2.0/default/snipcart.js"
       strategy="afterInteractive"/>


      <div hidden id="snipcart" data-api-key={process.env.
      NEXT_PUBLIC_SNIPCART_API_KEY} data-config-modal-style="none">
      </div>  


      <Navbar />

        {children}
      
        <Footer />
      </body>
    </html>
  </ClerkProvider>
  );
}
